---
- name: Install required packages via package manager
  ansible.builtin.package:
    name:
      - '{{ item }}'
    state: present
    become: true
  loop:
    - vim
    - git
    - powerline-fonts
    - fzf
    - zsh
  when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'RedHat'

- name: Check for homebrew installation script.
  ansible.builtin.stat:
    path: /tmp/homebrew.sh
  register: homebrew

- name: Get homebrew installation script.
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew.sh
    mode: 0755
  when: ansible_facts['distribution'] == 'MacOSX' and not homebrew.stat.exists

- name: Install homebrew from script.
  ansible.builtin.shell:
    cmd: '{{ item }}'
  with_items:
    - /bin/bash /tmp/homebrew.sh
  when: ansible_facts['distribution'] == 'MacOSX' and homebrew.stat.exists

- name: Install required packages via homebrew.
  community.general.homebrew:
    name:
      - '{{ item }}'
    state: latest
  with_items:
    - vim
    - zsh
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Install required packages via homebrew cask.
  community.general.homebrew_cask:
    name:
      - '{{ item }}'
    state: latest
  with_items:
    - iterm2
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Check for oh_my_zsh script
  ansible.builtin.stat:
    path: /tmp/oh-my-zsh.sh
  register: oh_my_zsh_script

- name: Get oh_my_zsh 
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh.sh
    mode: 0755
  when: not oh_my_zsh_script.stat.exists

- name: Check if oh_my_zsh is installed.
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/
  register: oh_my_zsh_installed

- name: Install oh-my-zsh.
  ansible.builtin.shell:
    cmd: '{{ item }}'
  with_items:
    - /bin/bash /tmp/oh-my-zsh.sh
  when: oh_my_zsh_script.stat.exists and not oh_my_zsh_installed.stat.exists
  
