---
- name: Install required packages via package manager
  ansible.builtin.package:
    name:
      - '{{ item }}'
    state: present
    become: true
  loop:
    - vim
    - git
    - powerline-fonts
    - fzf
    - zsh
  when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'RedHat'

- name: Get homebrew installation script.
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew.sh
    mode: 0755
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Install homebrew from script.
  ansible.builtin.script:
    chdir: /tmp/
    cmd: '{{ item }}'
    remote_src: true
  with_items:
    - homebrew.sh
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Install required packages via homebrew.
  community.general.homebrew:
    name:
      - '{{ item }}'
    state: latest
  with_items:
    - vim
    - zsh
    - iterm2
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Get oh_my_zsh 
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh.sh
    mode: 0755

- name: Install oh-my-zsh.
  ansible.builtin.script:
    chdir: /tmp/
    cmd: '{{ item }}'
    remote_src: true
  with_items:
    - oh-my-zsh.sh
  when: oh_my_zsh_downloaded is succeeded
