---
- name: Print ansible_facts.
  ansible.builtin.debug:
    var: ansible_facts

#- name: Install required packages via package manager
#  ansible.builtin.package:
#    name:
#      - '{{ item }}'
#    state: present
#    become: true
#  loop:
#    - vim
#    - git
#    - powerline-fonts
#    - fzf
#    - zsh
#  when: ansible_facts['ansible_distribution'] == 'Ubuntu' or ansible_facts['ansible_distribution'] == 'RedHat'
#
#- name: Get oh_my_zsh on Linux
#  ansible.builtin.get_url:
#    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
#    dest: /tmp/oh-my-zsh.sh
#    owner: root
#    group: root
#    mode: 0644
#  when: ansible_facts['ansible_distribution'] == 'Ubuntu' or ansible_facts['ansible_distribution'] == 'RedHat'
#
#- name: Get homebrew installation script.
#  ansible.builtin.get_url:
#    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
#    dest: /tmp/homebrew.sh
#    owner: root
#    group: wheel
#    mode: 0644
#  when: ansible_facts['ansible_distribution'] == 'OSX'
#
#- name: Get oh_my_zsh on Linux.
#  ansible.builtin.get_url:
#    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
#    dest: /tmp/oh-my-zsh.sh
#    owner: root
#    group: wheel
#    mode: 0644
#  register: oh_my_zsh_downloaded
#  when: ansible_facts['ansible_distribution'] == 'OSX'
#
#- name: Install homebrew from script.
#  ansible.builtin.script:
#    cmd:
#      - /tmp/homebrew.sh
#  when: ansible_facts['ansible_distribution'] == 'OSX'
#
#- name: Install required packages via homebrew.
#  community.general.homebrew:
#    name:
#      - '{{ item }}'
#    state: latest
#  loop:
#    - vim
#    - zsh
#    - iterm2
#  when: ansible_facts['ansible_distribution'] == 'OSX'
#
#- name: Get oh_my_zsh on Mac OSX.
#  ansible.builtin.get_url:
#    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
#    dest: /tmp/oh-my-zsh.sh
#    owner: root
#    group: wheel
#    mode: 0644
#  register: oh_my_zsh_downloaded
#  when: ansible_facts['ansible_distribution'] == 'OSX'
#
#- name: Install oh-my-zsh.
#  ansible.builtin.shell:
#    cmd:
#      - /tmp/oh-my-zsh.sh
#  when: oh_my_zsh_downloaded is succeeded
#