---
- name: "Set variable required_packages to false."
  ansible.builtin.set_fact:
    required_packages: false

- name: "Get repositories gpg key and add repositories for required packages."
  block:

    - name: "Add repositories gpg key for required packages."
      become: true
      ansible.builtin.get_url:
        url: "{{ key.url }}"
        dest: "/etc/pki/rpm-gpg/{{ key.filename }}"
        owner: "root"
        group: "root"
        mode: "0o644"
      loop:
        - {
            url: "https://packages.opentofu.org/opentofu/tofu/gpgkey",
            filename: "opentofu.asc"
          }
        - {
            url: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg",
            filename: "vscodium.asc"
          }
        - {
            url: "https://rpm.releases.hashicorp.com/gpg",
            filename: "hashicorp.asc"
          }
        - {
            url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg",
            filename: "google_cloud.asc"
          }
        - {
            url: "https://packages.microsoft.com/keys/microsoft.asc",
            filename: "microsoft.asc"
          }
        - {
            url: "https://raw.githubusercontent.com/eza-community/eza/main/deb.asc",
            filename: "eza_community.asc"
          }
      loop_control:
        loop_var: key

    - name: "Add repositories for required packages."
      become: true
      ansible.builtin.yum_repository:
        name: "{{ repositiory.name }}"
        baseurl: "{{ repository.baseurl }}"
        state: present
        gpgkey: "/etc/pki/rpm-gpg/{{ repository.gpgkey }}"
        gpgcheck: true
        enabled: true
      loop:
        - {
            name: "opentofu",
            baseurl: "https://packages.opentofu.org/opentofu/tofu/rpm_any/rpm_any/$basearch",
            gpgkey: "opentofu.asc"
          }
        - {
            name: "vscodium",
            baseurl: "https://download.vscodium.com/rpms/",
            gpgkey: "vscodium.asc"
          }
        - { 
            name: "hashicorp",
            baseurl: "https://rpm.releases.hashicorp.com/fedora/hashicorp.repo",
            gpgkey: "hashicorp.asc"
          }
        - {
            name: "Google Cloud",
            baseurl: "https://packages.cloud.google.com/rpm/",
            gpgkey: "cloud_google.asc"
          }
        - {
            Name: "Microsoft",
            baseurl: "https://packages.microsoft.com/repos/azure-cli/",
            gpgkey: "microsoft.asc"
          } 
        - {
            name: "Eza Community",
            baseurl: "http://deb.gierens.de",
            gpgkey: "eza_community.asc"
          }
      loop_control:
        loop_var: repository

- name: "Updated DNF Cache"
  become: true
  ansible.builtin.dnf:
    update_cache: true
  register: dnf_cache_updated

- name: "Install required packages via dnf."
  become: true
  ansible.builtin.dnf:
    name: "{{ dnf_package.name }}"
    state: latest
  loop:
    - { name: "firefox" }
    - { name: "vim"}
    - { name: "zsh"}
    - { name: "ruby"}
    - { name: "golang"}
    - { name: "python3.11" }
    - { name: "git" }
    - { name: "cmake" }
    - { name: "nodejs" }
    - { name: "gpg" }
    - { name: "openssh-server" }
    - { name: "zsh" }
    - { name: "konsole" }
    - { name: "codium" }
    - { name: "google-cloud-sdk" }
    - { name: "awscli" }
    - { name: "azure-cli" }
    - { name: "eza" }
    - { name: "tofu" }
    - { name: "packer" } # TODO: if open source replacement becomes availabe, then we will replace.
    - { name: "vault" } # TODO: if open source replacement becomes availabe, then we will replace.
  loop_control:
    loop_var: apt_package
  when: dnf_cache_updated is changed

- name: "Set variable required_packages to true."
  ansible.builtin.set_fact:
    required_packages: true
