---
- name: Get get installation script.
  ansible.builtin.get_url:
    url: '{{ script.url }}'
    dest: '{{ script.name }}'
    mode: 0755
  loop:
    - { url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh , name: /tmp/homebrew.sh }
  loop_control:
    loop_var: script

- name: Install homebrew from script.
  ansible.builtin.shell:
    cmd: /bin/bash /tmp/homebrew.sh

- name: Install required packages via homebrew.
  community.general.homebrew:
    name: '{{ brew_package.name }}'
    state: '{{ brew_package.state }}'
  loop:
    - { name: 'vim', state: 'latest' }
    - { name: 'zsh', state: 'latest' }
    - { name: 'ruby', state: 'latest' }
    - { name: 'go', state: 'latest' }
    - { name: 'python@3.11', state: 'latest' }
    - { name: 'git', state: 'latest' }
    - { name: 'eza', state: 'latest' }
    - { name: 'cmake', state: 'latest' }
    - { name: 'node', state: 'latest' }
    - { name: 'gpg', state: 'latest' }
    - { name: 'openssh', state: 'latest' }
    - { name: 'powerlevel10k', state: 'latest' }
    - { name: 'zsh-autosuggestions', state: 'latest' }
    - { name: 'zsh-syntax-highlighting', state: 'latest' }
    - { name: 'zsh-completions', state: 'latest' }
    - { name: 'zsh-history-substring-search', state: 'latest' }  
    - { name: 'zsh-autopair', state: 'latest' }
  loop_control:
    loop_var: brew_package

- name: Tap casks for Homebrew
  community.general.homebrew_tap:
    name: '{{ homebrew_tap.name }}'
    state: '{{ homebrew_tap.state }}'
  loop:
    - { name: 'homebrew/cask-fonts', state: 'present'}
    - { name: 'hashicorp/tap', state: 'present'}
  loop_control:
    loop_var: homebrew_tap

- name: Install required packages via homebrew cask.
  community.general.homebrew_cask:
    name: '{{ cask_package.name }}'
    state: '{{ cask_package.state }}'
  loop:
    - { name: 'iterm2', state: 'latest' }
    - { name: 'font-hack-nerd-font', state: 'latest' }
    - { name: 'google-cloud-sdk', state: 'latest' }
    - { name: 'terraform', state: 'latest'}
    - { name: 'packer', state: 'latest'}
    - { name: 'vault', state: 'latest'}
  loop_control:
    loop_var: cask_package
