---
- name: "Set variable required_packages to true."
  ansible.builtin.set_fact:
    required_packages: false

- name: "Get get installation script."
  become: true
  ansible.builtin.get_url:
    url: "{{ script.url }}"
    dest: "{{ script.name }}"
    mode: "0o700"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  loop:
    - { url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh", name: "/tmp/homebrew.sh" }
  loop_control:
    loop_var: script
  register: download_homebrew
  notify: Install homebrew from script.

- name: "Flush Handlers"
  ansible.builtin.meta: flush_handlers
  when: download_homebrew is changed

- name: "Install required packages via homebrew."
  community.general.homebrew:
    name: "{{ brew_package.name }}"
    state: latest
  loop:
    - { name: "vim" }
    - { name: "zsh" }
    - { name: "ruby" }
    - { name: "go" }
    - { name: "python@3.12" }
    - { name: "git" }
    - { name: "eza" }
    - { name: "cmake" }
    - { name: "gcc" }
    - { name: "node" }
    - { name: "gpg" }
    - { name: "openssh" }
    - { name: "awscli" }
    - { name: "azure-cli" }
    - { name: "xclip" }
    - { name: "tofu" }
  loop_control:
    loop_var: brew_package

- name: "Tap casks for Homebrew"
  community.general.homebrew_tap:
    name: "{{ tap.name }}"
    state: present
  loop:
    - { name: "hashicorp/tap" }
  loop_control:
    loop_var: tap

- name: "Install required packages via homebrew cask."
  community.general.homebrew_cask:
    name: "{{ cask.name }}"
    state: latest
  loop:
    - { name: "kitty" }
    - { name: "vscodium" }
    - { name: "google-cloud-sdk" }
    - { name: "terraform" }
    - { name: "packer" }
    - { name: "vault" }
  loop_control:
    loop_var: cask

- name: "Set variable required_packages to true."
  ansible.builtin.set_fact:
    required_packages: true
