---
- name: "Set variable required_packages to false."
  ansible.builtin.set_fact:
    required_packages: false

- name: "Install terminal from hyper.is"
  block:
    - name: "Download Hyper Terminal package."
      ansible.builtin.get_url:
        url: "https://releases.hyper.is/download/rpm"
        dest: "/tmp/hyper_amd64.rpm"
        mode: "0o655"
        owner: "{{ ansible_facts['user_uid'] }}"
        group: "{{ ansible_facts['user_gid'] }}"

    - name: "Install Hyper Terminal."
      become: true
      ansible.builtin.dnf:
        dnf: "/tmp/hyper_amd64.rpm" 

- name: "Add repositories for required packages."
  become: true
  ansible.builtin.yum_repository:
    name: "{{ repository.name }}"
    description: "{{ repository.description }}"
    baseurl: "{{ repository.baseurl }}"
    state: present
    gpgkey: "{{ repository.gpgkey }}"
    gpgcheck: true
    enabled: true
  loop:
    - {
        name: "opentofu",
        description: "opentofu",
        baseurl: "https://packages.opentofu.org/opentofu/tofu/rpm_any/rpm_any/$basearch",
        gpgkey: ["https://get.opentofu.org/opentofu.gpg","https://packages.opentofu.org/opentofu/tofu/gpgkey"]
      }
    - {
        name: "vscodium",
        description: "vscodium",
        baseurl: "https://download.vscodium.com/rpms/",
        gpgkey: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg"
      }
    - { 
        name: "hashicorp",
        description: "hashicorp",
        baseurl: "https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable",
        gpgkey: "https://rpm.releases.hashicorp.com/gpg"
      }
    - {
        name: "google_cloud",
        description: "google cloud",
        baseurl: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64",
        gpgkey: "https://packages.cloud.google.com/apt/doc/rpm-package-key.gpg"
      }
    - {
        name: "microsoft",
        description: "microsoft",
        baseurl: "https://packages.microsoft.com/fedora/{{ fedora_version }}/prod/",
        gpgkey: "https://packages.microsoft.com/fedora/{{ fedora_version }}/prod/repodata/repomd.xml.key"
      } 
  loop_control:
    loop_var: repository

- name: "Updated DNF Cache"
  become: true
  ansible.builtin.dnf:
    update_cache: true
  register: dnf_cache_updated

- name: "Install required packages via dnf."
  become: true
  ansible.builtin.dnf:
    name: "{{ dnf_package.name }}"
    state: latest
  loop:
    - { name: "hyper" }
    - { name: "firefox" }
    - { name: "vim" }
    - { name: "rustc" }
    - { name: "ruby" }
    - { name: "golang" }
    - { name: "clang" }
    - { name: "python3.11" }
    - { name: "python3-devel" }
    - { name: "git" }
    - { name: "cmake" }
    - { name: "nodejs" }
    - { name: "gpg" }
    - { name: "openssh-server" }
    - { name: "zsh" }
    - { name: "konsole" }
    - { name: "codium" }
    - { name: "google-cloud-sdk" }
    - { name: "awscli" }
    - { name: "azure-cli" }
    - { name: "eza" }
    - { name: "xclip" }
    - { name: "tofu" }
    - { name: "packer" } # TODO: if open source replacement becomes availabe, then we will replace.
    - { name: "vault" } # TODO: if open source replacement becomes availabe, then we will replace.
  loop_control:
    loop_var: dnf_package
  #when: dnf_cache_updated is changed

- name: "Set variable required_packages to true."
  ansible.builtin.set_fact:
    required_packages: true
