---
- name: Install required packages via package manager
  ansible.builtin.package:
    name:
      - '{{ package.name }}'
    state: '{{ package.state }}'
    become: true
  loop:
    - { name: 'vim', state: 'present' }
    - { name: 'git', state: 'present' }
    - { name: 'powerline-fonts', state: 'present' }
    - { name: 'zsh', state: 'present' }
  loop_control:
    loop_var: package
  when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'RedHat'

- name: Get get installation script.
  ansible.builtin.get_url:
    url: '{{ script.url }}'
    dest: '{{ script.name }}'
    mode: 0755
  loop:
    - { url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh , name: /tmp/homebrew.sh }
  loop_control:
    loop_var: script
  when: ansible_facts['distribution'] == 'MacOSX' and not homebrew.stat.exists

- name: Install homebrew from script.
  ansible.builtin.shell:
    cmd: /bin/bash /tmp/homebrew.sh
  when: ansible_facts['distribution'] == 'MacOSX' and homebrew.stat.exists

- name: Install required packages via homebrew.
  community.general.homebrew:
    name: '{{ brew_package.name }}'
    state: '{{ brew_package.state }}'
  loop:
    - { name: 'vim', state: 'latest' }
    - { name: 'zsh', state: 'latest' }
    - { name: 'ruby', state: 'latest' }
    - { name: 'vault', state: 'latest' }
    - { name: 'terraform', state: 'latest' }
    - { name: 'go', state: 'latest' }
    - { name: 'python@3.11', state: 'latest' }
    - { name: 'git', state: 'latest' }
    - { name: 'packer', state: 'latest' }
    - { name: 'exa', state: 'latest' }
  loop_control:
    loop_var: brew_package
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Tap homebrew repositories.
  community.general.homebrew_tap:
    name: '{{ cask_repo.name }}'
    state: '{{ cask_repo.state }}'
  loop:
    - {name: 'homebrew/cask-fonts', state: 'present' }
  loop_control:
    loop_var: cask_repo
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Install required packages via homebrew cask.
  community.general.homebrew_cask:
    name: '{{ cask_package.name }}'
    state: '{{ cask_package.state }}'
  with_items:
    - { name: 'iterm2', state: 'latest' }
    - { name: 'font-hack-nerd-font', state: 'latest' }
  loop_control:
    loop_var: cask_package
  when: ansible_facts['distribution'] == 'MacOSX'
