---
# tasks file for setup-shell
- name: Setup Shell
  ansible.builtin.import_tasks:
    file:
      - tasks/install_requirements.yml
      - tasks/setup_oh_my_zsh.yml
      - tasks/setup_zsh.yml
      - tasks/setup_vim.yml
