---
# tasks file for automate os shell

- name: Import install_requirements
  ansible.builtin.import_tasks: '(( item }}'
  with_items:
    - install_requirements.yml
    - setup_oh_my_zsh.yml
    - setup_zsh.yml
    - setup_vim.yml
