---
# tasks file for setup-shell
- name: Print facts.
  ansible.builtin.debug:
    var: ansible_facts['distribution']

- name: Install required packages for MacOS
  ansible.builtin.include_tasks:
    file:
      - install_requirements_darwin.yml
  when: ansible_facts['distribution'] == 'Darwin'

- name: Install required packages for Debian
  ansible.builtin.include_tasks:
    file:
      - install_requirements_debian.yml
  when: ansible_facts['distribution'] == 'Debian'

- name: Install required packages for RedHat
  ansible.builtin.include_tasks:
    file:
      - install_requirements_redhat.yml
  when: ansible_facts['distribution'] == 'RedHat'

- name: Setup shell for *nix type systems.  
  ansible.builtin.include_tasks:
    file:
      - setup_zsh.yml
      - setup_powerlevel_10k.yml
      - setup_vim.yml
