--- 
- name: "Set variable configure_vim to false."
  ansible.builtin.set_fact:
    configure_vim: false

- name: Create .vim folder
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/{{ plugin.name }}"
    state: directory
    mode: "0o700"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  loop:
    - { name: "SimpylFold" }
    - { name: "indentpython" }
    - { name: "YouCompleteMe" }
    - { name: "syntastic" }
    - { name: "vim-flake8" }
    - { name: "Zenburn" }
    - { name: "Base2Tone-vim" }
    - { name: "nerdtree" }
    - { name: "vim-nerdtree-tabs" }
    - { name: "ctrlp" }
    - { name: "vim-fugitive" }
    - { name: "powerline" }
    - { name: "vimspector" }
    - { name: "vim-terraform" }
    - { name: "ansible-vim" }
    - { name: "vim-go" }
    - { name: "fugitive-gitlab.vim" }
    - { name: "vim-javascript" }
    - { name: "vim-javascript-syntax" }
    - { name: "vim-prettier" }
    - { name: "zig.vim" }
  loop_control:
    loop_var: plugin

- name: "Copy files to {{ ansible_facts['user_dir'] }}"
  ansible.builtin.copy:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    mode: "0o600"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  loop:
    - { src: ".inputrc", dest: "{{ ansible_facts['user_dir'] }}/.inputrc" } 
    - { src: ".vimrc", dest: "{{ ansible_facts['user_dir'] }}/.vimrc" }
  loop_control:
    loop_var: file

- name: Install vim plugins
  ansible.builtin.git:
    repo: "{{ git.repo }}"
    dest: "{{ git.dest }}"
    clone: true
    update: true
  loop:
    - { repo: "git@github.com:tmhedberg/SimpylFold.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/SimpylFold" }
    - { repo: "git@github.com:vim-scripts/indentpython.vim.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/indentpython" }
    - { repo: "git@github.com:ycm-core/YouCompleteMe.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/YouCompleteMe" }
    - { repo: "git@github.com:vim-syntastic/syntastic.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/syntastic" }
    - { repo: "git@github.com:nvie/vim-flake8.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-flake8" }
    - { repo: "git@github.com:jnurmine/Zenburn.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/Zenburn" }
    - { repo: "git@github.com:atelierbram/Base2Tone-vim.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/Base2Tone-vim" }
    - { repo: "git@github.com:preservim/nerdtree.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/nerdtree/start" }
    - { repo: "git@github.com:jistr/vim-nerdtree-tabs.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-nerdtree-tabs" }
    - { repo: "git@github.com:kien/ctrlp.vim.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/ctrlp" }
    - { repo: "git@github.com:tpope/vim-fugitive.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-fugitive" }
    - { repo: "git@github.com:powerline/powerline.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/powerline" }
    - { repo: "git@github.com:puremourning/vimspector.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vimspector" }
    - { repo: "git@github.com:hashivim/vim-terraform.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-terraform" }
    - { repo: "git@github.com:pearofducks/ansible-vim.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/ansible-vim" }
    - { repo: "git@github.com:fatih/vim-go.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-go" }
    - { repo: "git@github.com:shumphrey/fugitive-gitlab.vim.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/fugitive-gitlab.vim" }
    - { repo: "git@github.com:pangloss/vim-javascript.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-javascript" }
    - { repo: "git@github.com:jelera/vim-javascript-syntax.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-javascript-syntax" }
    - { repo: "git@github.com:prettier/vim-prettier.git", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/vim-prettier" }
    - { repo: "git@github.com:ziglang/zig.vim", dest: "{{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/zig.vim" }
  loop_control:
    loop_var: git

- name: Compile YouCompleteMe
  ansible.builtin.command:
    cmd: python3 {{ ansible_facts['user_dir'] }}/.vim/pack/vendor/start/YouCompleteMe/install.py

- name: "Set variable configure_vim to true."
  ansible.builtin.set_fact:
    configure_vim: true
