---
- name: Check if PowerLevel10K is installed.
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k_installed

- name: Install PowerLevel10K.
  ansible.builtin.git:
    repo: git@github.com:romkatv/powerlevel10k.git
    dest: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
    clone: true
  when: not powerlevel10k_installed.stat.exists

- name: Update PowerLevel10K.
  ansible.builtin.git:
    repo: git@github.com:romkatv/powerlevel10k.git
    dest: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
    update: true
  when: powerlevel10k_installed.stat.exists

#- name: Check for PowerLevel10K configuration.
#  ansible.builtin.stat:
#    path: $HOME/.p10k.zsh
#  register: p10k_configuration
