---
- name: "Set variable setup_powerlevel10k to false."
  ansible.builtin.set_fact:
    setup_powerlevel10k: false

- name: Copy PowerLevel10K configuration.
  ansible.builtin.copy:
    src: ".p10k.zsh"
    dest: "{{ ansible_facts['user_dir'] }}/.p10k.zsh"
    mode: "0o700"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"

- name: "Set variable setup_powerlevel10k to true."
  ansible.builtin.set_fact:
    setup_powerlevel10k: true