---
- name: Check if .zshrc file exists.
  ansible.builtin.stat:
    path: $HOME/.zshrc
  register: zshrc

- name: Create a .zshrc file.
  ansible.builtin.template:
    path: /template/.zshrc.j2
    dest: $HOME/.zshrc
    mode: 0644
  when: not zshrc.stat.exists

- name: Add Plugins to .zshrc file.
  ansible.builtin.lineinfile:
    path: $HOME/.zshrc
    regexp: '^plugins=(git)$'
    line: 'plugins=(git zsh-syntax-highlighting zsh-autosuggestions)'
    state: present
  when: zshrc.stat.exists

- name: Update .zsh theme to powerlevel10k.
  ansible.builtin.lineinfile:
    path: $HOME/.zshrc
    regexp: '^ZSH_THEME=robbyrussell$'
    line: ZSH_THEME='powerlevel10k/powerlevel10k'
    state: present
  when: zshrc.stat.exists

- name: Enable p10k instant prompt.
  ansible.builtin.lineinfile:
    path: $HOME/.zshrc
    line: >-
      'if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
      source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
      fi'
    state: present

- name: Export env and other important information
  ansible.builtin.lineinfile:
    path: $HOME/.zshrc
    line: >-
      ' export PATH=/opt/homebrew/bin:$PATH \
        export ANSIBLE_VAULT_PASSWORD_FILE=$HOME/ansible_vault \
        export VAULT_ADDR=https://ssdlc-vault.soc.int.bell.ca \
        export VAULT_CACERT=/etc/ssl/certs/ssdlc-vault.soc.int.bell.ca.pem \
        export NO_PROXY='{{ no_proxy }}' \
        export HTTP_PROXY=http://fastweb.int.bell.ca:80 \
        export http_proxy=http://fastweb.int.bell.ca:80 \
        export HTTPS_proxy=http://fastweb.int.bell.ca:80 \
        export https_proxy=http://fastweb.int.bell.ca:80 \

        ssh-add $HOME/.ssh/ua_jumpbox_id_rsa \
        ssh-add $HOME/.ssh/ut_jumpbox_id_rsa \
        ssh-add $HOME/.ssh/ug_jumpbox_id_rsa \
        ssh-add $HOME/.ssh/ug_id_rsa \
        ssh-add $HOME/.ssh/google_compute_engine \
      '
    state: present