---
- name: Get oh_my_zsh 
  ansible.builtin.get_url:
    url: '{{ script.url }}'
    dest: '{{ script.dest }}'
    mode: 0755
  loop:
    - { url: 'https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh', dest: '/tmp/oh-my-zsh.sh'}
  loop_control:
    loop_var: script

- name: Check oh-my-zsh install
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh
  register: oh_my_zsh_installed

- name: Install oh-my-zsh.
  ansible.builtin.shell:
    cmd: /bin/bash /tmp/oh-my-zsh.sh
  when: not oh_my_zsh_installed.stat.exists

- name: Install colorls
  community.general.gem:
    name: '{{ gem.name }}'
    state: '{{ gem.state }}'
  loop:
    - { name: 'colorls', state: 'latest' }
  loop_control:
    loop_var: gem
