---

- name: Copy .zshrc configuration.
  ansible.builtin.template:
    src:  ./templates/.zshrc
    dest: "{{ ansible_facts['user_dir'] }}/.zshrc"
    mode: "0o700"
  register: "zshrc_copied"
  notify: "Source .zshrc"

- name: Source .zshrc
  ansible.builtin.meta: flush_handlers
  