---

- name: Copy .zshrc configuration.
  ansible.builtin.template:
    src:  debian_zshrc.j2
    dest: "{{ ansible_facts['user_dir'] }}/.zshrc"
    mode: "0o700"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['group_id'] }}"
  register: zshrc_copied
  notify: Source .zshrc
  when: ansible_facts["os_family"] | lower == "debian"

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
  