---
- name: Get MesloLGS Fonts.
  ansible.builtin.get_url:
    url: "{{ font.url }}"
    dest: $HOME/Library/Fonts/{{ font.name }}
    mode: 0644
  loop:
    - {url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf", name: "MesloLGS_NF_Regular.ttf"}
    - {url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf", name: "MesloLGS_NF_Bold.ttf"}
    - {url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf", name: "MesloLGS_NF_Italic.ttf"}
    - {url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf", name: "MesloLGS_NF_Bold_Italic.ttf"}
  loop_control:
    loop_var: font

- name: Copy PowerLevel10K configuration.
  ansible.builtin.copy:
    src: files/.p10k.zsh
    dest: $HOME/.p10k.zsh
    mode: 0700
