---
- name: Install PowerLevel10K.
  ansible.builtin.git:
    repo: '{{ git.repo }}'
    dest: '{{ git.dest }}'
    clone: true
    update: true
  loop:
    - { repo: 'git@github.com:romkatv/powerlevel10k.git', dest: '$HOME/.oh-my-zsh/custom/themes/powerlevel10k' }
  loop_control:
    loop_var: git

- name: Copy PowerLevel10K configuration.
  ansible.builtin.copy:
    src: files/.p10k.zsh
    dest: $HOME/.pk10k.zsh
    mode: 0700
