---
- name: Check for oh_my_zsh script
  ansible.builtin.stat:
    path: /tmp/oh-my-zsh.sh
  register: oh_my_zsh_script

- name: Get oh_my_zsh 
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh.sh
    mode: 0755
  when: not oh_my_zsh_script.stat.exists

- name: Check if oh_my_zsh is installed.
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/
  register: oh_my_zsh_installed

- name: Install oh-my-zsh.
  ansible.builtin.shell:
    cmd: /bin/bash /tmp/oh-my-zsh.sh
  when: oh_my_zsh_script.stat.exists and not oh_my_zsh_installed.stat.exists
  
- name: Check if oh-my-zsh folder exists.
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/custom/plugins/
  register: oh_my_zsh_plugins

- name: Check if zsh-syntax-highlighting exists.
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  register: zsh_syntax_highlighting
  when: oh_my_zsh_plugins.stat.exists

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-syntax-highlighting.git
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighing
    clone: true
  when: not zsh_syntax_highlighting.stat.exists

- name: Update zsh syntax highlighting
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-syntax-highlighting.git
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighing
    update: true
  when: zsh_syntax_highlighting.stat.exists

- name: Check if zsh-autosuggstions exists
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  register: zsh_autosuggestions
  when: oh_my_zsh_plugins.stat.exists

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-autosuggestions.git
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: true
  when: not zsh_autosuggestions.stat.exists

- name: Update zsh auto-suggestions
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-autosuggestions.git
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: true
  when: zsh_autosuggestions.stat.exists

- name: Install colorls
  community.general.gem:
    name: '{{ gem }}'
    state: latest
  with_items:
    - colorls
  loop_control:
    loop_var: gem
