---
- name: "Set fact codium_configured to false."
  ansible.builtin.set_fact:
    configure_codium: false

- name: "Copy codium settings file on Darwin systems."
  ansible.builtin.git:
    src: settings.json
    dest: "{{ ansible_facts['user_dir'] }}/Library/Application Support/VSCodium/User/"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0o644"
  when: ansible_facts['os_family'] | lower == 'darwin'

- name: "Copy codium settings file on Linux Systems."
  ansible.builtin.copy:
    src: settings.json
    dest: "{{ ansible_facts['user_dir'] }}/.config/VSCodium/User/"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0o644"
  when: ansible_facts['system'] | lower == 'linux'

- name: "Set fact codium_configured to true."
  ansible.builtin.set_fact:
    configure_codium: true
 
