---
- name: "Set variable setup_powerlevel10k to false."
  ansible.builtin.set_fact:
    setup_zsh: false

- name: "Copy .zshrc configuration on {{ ansible_facts['system'] | lower }} systems."
  ansible.builtin.template:
    src:  "nix_zshrc.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.zshrc"
    mode: "0o700"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  register: zshrc_copied
  when: ansible_facts['system'] | lower == 'linux'

- name: "Copy .zshrc configuration on {{ ansible_facts['os_family'] | lower }} systems."
  ansible.builtin.template:
    src:  "darwin_zshrc.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.zshrc"
    mode: "0o700"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  register: zshrc_copied
  notify:
    - "Run commands to init zsh add-ons"
  when: ansible_facts["os_family"] | lower  == "darwin"

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
  when: zshrc_copied is changed

- name: "Set variable setup_powerlevel10k to true."
  ansible.builtin.set_fact:
    setup_zsh: true
  