---
- name: Create .vim folder
  ansible.builtin.file:
    path: $HOME/.vim/pack/{plugin.name}/start
    state: directory
  loop:
    - {name: 'Vundle'}
    - {name: 'SimpylFold'}
    - {name: 'indentpython'}
    - {name: 'YouCompleteMe'}
    - {name: 'syntastic'}
    - {name: 'vim-flake8'}
    - {name: 'Zenburn'}
    - {name: 'vim-colors-solarized'}
    - {name: 'nerdtree'}
    - {name: 'vim-nerdtree-tabs'}
    - {name: 'ctrlp'}
    - {name: 'vim-fugitive'}
    - {name: 'powerline'}

  loop_control:
    loop_var: plugin

- name: Copy files to $HOME
  ansible.builtin.copy:
    src: '{{ file.src }}'
    dest: '{{ file.dest }}'
    mode: 0644
  loop:
    - { src: 'files/.inputrc', dest: '$HOME/.inputrc' } 
    - { src: 'files/.vimrc', dest: '$HOME/.vimrc' }
  loop_control:
    loop_var: file

- name: Install vim plugins
  ansible.builtin.git:
    repo: '{{ git.repo }}'
    dest: '{{ git.dest }}'
    clone: true
    update: true
  loop:
    - { repo: 'git@github.com:VundleVim/Vundle.vim.git', dest: '$HOME/.vim/pack/Vundle/start' }
    - { repo: 'git@github.com:tmhedberg/SimpylFold.git', dest: '$HOME/.vim/pack/SimpylFold/start' }
    - { repo: 'git@github.com:vim-scripts/indentpython.vim.git', dest: '$HOME/.vim/pack/indentpython/start' }
    - { repo: 'git@github.com:ycm-core/YouCompleteMe.git', dest: '$HOME/.vim/pack/YouCompleteMe/start' }
    - { repo: 'git@github.com:vim-syntastic/syntastic.git', dest: '$HOME/.vim/pack/syntastic/start' }
    - { repo: 'git@github.com:nvie/vim-flake8.git', dest: '$HOME/.vim/pack/vim-flake8/start' }
    - { repo: 'git@github.com:jnurmine/Zenburn.git', dest: '$HOME/.vim/pack/Zenburn/start' }
    - { repo: 'git@github.com:altercation/vim-colors-solarized.git', dest: '$HOME/.vim/pack/vim-colors-solarized/start' }
    - { repo: 'git@github.com:preservim/nerdtree.git', dest: '$HOME/.vim/pack/nerdtree/start' }
    - { repo: 'git@github.com:jistr/vim-nerdtree-tabs.git', dest: '$HOME/.vim/pack/vim-nerdtree-tabs/start' }
    - { repo: 'git@github.com:kien/ctrlp.vim.git', dest: '$HOME/.vim/pack/ctrlp/start' }
    - { repo: 'git@github.com:tpope/vim-fugitive.git', dest: '$HOME/.vim/pack/vim-fugitive/start' }
    - { repo: 'git@github.com:powerline/powerline.git', dest: '$HOME/.vim/pack/powerline/start' }
  loop_control:
    loop_var: git

- name: Configure YouCompleteMe
  ansible.builtin.shell:
    cmd: python3 $HOME/.vim/pack/YouCompleteMe/start/install.py
