---
- name: "Set variable configure_hyper to false."
  ansible.builtin.set_fact:
    configure_hyper: false

- name: "Create Hyper Plugin directories."
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.hyper_plugins/local"
    state: "directory"
    mode: "0o700"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
- name: copy hyper.js configuration file.
  ansible.builtin.copy:
    src: .hyper.js
    dest: "{{ ansible_facts['user_dir'] }}/.hyper.js"
    mode: "0o400"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"

- name: "Set variable configure_hyper to true."
  ansible.builtin.set_fact:
    configure_hyper: true
