---
- name: Clone .vim_runtime
  ansible.builtin.git:
    repo: git@github.com:amix/vimrc.git
    dest: $HOME/.vim_runtime
    clone: true

- name: Install awesome vimrc.
  ansible.builtin.script:
    cmd:
      - $HOME/.vim_runtime/install_awesome_vimrc.sh
    remote_src: true
