---
- name: Source .zshrc
  ansible.builtin.shell:
    cmd: "source {{ ansible_facts['user_dir'] }}/.zshrc"
  args:
    executable: /bin/bash

- name: Install homebrew from script.
  ansible.builtin.shell:
    cmd: /tmp/homebrew.sh
  args:
    executable: /bin/zsh
